artifacts_root: "artifacts"
# step 1 data ingestion config
data_ingestion:
  root_dir: "artifacts/data_ingestion"
  source_URL: "https://raw.githubusercontent.com/Dadaranger/dataset/main/winequality-white.zip"
  local_data_file: "artifacts/data_ingestion/data.zip"
  unzip_dir: "artifacts/data_ingestion"
# step 2 data validation config
data_validation:
  root_dir: "artifacts/data_validation"
  unzip_data_dir: "artifacts/data_ingestion/winequality-white.csv"
  STATUS_FILE: "artifacts/data_validation/status.txt"

# step 3 data transformation config
data_transformation:
  root_dir: "artifacts/data_transformation"
  data_path: "artifacts/data_ingestion/winequality-white.csv"

# step 4 model training config
model_training:
  root_dir: "artifacts/model_training"
  train_data_path: "artifacts/data_transformation/train.csv"
  test_data_path: "artifacts/data_transformation/test.csv"
  model_name: model.joblib

# step 5 model evaluation config
model_evaluation:
  root_dir: "artifacts/model_evaluation"
  test_data_path: "artifacts/data_transformation/test.csv"
  model_path: "artifacts/model_training/model.joblib"
  metrics_file_name: "artifacts/model_evaluation/metrics.json"