artifacts_root: "artifacts"
# step 1 data ingestion config
data_ingestion:
  root_dir: "artifacts/data_ingestion"
  source_URL: "https://raw.githubusercontent.com/Dadaranger/dataset/main/winequality-white.zip"
  local_data_file: "artifacts/data_ingestion/data.zip"
  unzip_dir: "artifacts/data_ingestion"
# step 2 data validation config
data_validation:
  root_dir: "artifacts/data_validation"
  unzip_data_dir: "artifacts/data_ingestion/winequality-white.csv"
  STATUS_FILE: "artifacts/data_validation/status.txt"

# step 3 data transformation config
data_transformation:
  root_dir: "artifacts/data_transformation"
  data_path: "artifacts/data_ingestion/winequality-white.csv"